### ISSUE TITLE
localconfig doesn't change style source value

### ISSUE THREAD

**Issue by pnorman** [kosmtik/kosmtik#189] opened 2016-11-24 00:41 UTC
I have a style YAML with

```yaml
source: "tmsource:///home/user/path/to/meddo"
```
and localconfig.json with
```json
[
  {
    "where": "source",
    "then": "tmsource:///home/pnorman/osm/meddo"
  }
]
```

When I try to serve with kosmtik I get

```
[Local Config] Patched config from /home/pnorman/osm/osm-bright-kartotherian/localconfig.json
[datasource loader] Loading source from /home/user/path/to/meddo
fs.js:839
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/home/user'
```

**Comment by yohanboniface** [comment] 2016-11-29 08:35
Yes, it's about order of events. I want to fix that.
You know you can have relative path as source?

Closing, it's a duplicate of https://github.com/kosmtik/kosmtik/issues/127 ;)

**Closed by yohanboniface** 2016-11-29 08:35 UTC
