### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by BorisHollas** [kosmtik/kosmtik#155] opened 2016-06-26 20:32 UTC
With npm 3.5.2 and node.js 4.2.6, I get

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mapnik@3.5.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mapnik@3.5.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/kosmtik/npm-debug.log

**Comment by nebulon42** [comment] 2016-06-26 20:39
Looks like the node-mapnik library (https://github.com/mapnik/node-mapnik) fails to install. Maybe there are no binaries for 16.04 (yet). I think it would be best to ask over there at node-mapnik. Or try to install node-mapnik for itself by calling `npm install mapnik@3.5.13` in the Kosmtik directory and see what the output is. Unfortunately, I'm still on 14.04 so I cannot reproduce locally.

**Comment by BorisHollas** [comment] 2016-06-26 20:44
Thanks for the quick reply. Yes, node-mapnik fails to install. I'll report the problem there.

**Comment by nebulon42** [comment] 2016-06-27 17:12
See https://github.com/mapnik/node-mapnik/issues/662. I'm closing here.

**Closed by nebulon42** 2016-06-27 17:12 UTC

**Comment by math1985** [comment] 2016-09-18 19:51
For what it's worth, I can reproduce this issue.

**Comment by math1985** [comment] 2016-09-18 20:46
I can confirm this issue, and it seems indeed to be a node-mapnik problem.

**Comment by math1985** [comment] 2016-09-18 23:59
This problem can be solved with sudo apt-get install nodejs-legacy (perhaps in combination with uninstalling the regular nodejs).
