### ISSUE TITLE
failed npm install on Ubuntu 14.04 and npm 1.4.9 - "Failed at the mapnik@3.4.0 install script."

### ISSUE THREAD

**Issue by matkoniecz** [kosmtik/kosmtik#69] opened 2015-07-07 05:39 UTC
After npm install that outputed significant amount of "npm http GET" and failed at the end I started it again and it failed again with exactly the same issue:

```
mateusz@Grisznak:~/Desktop/tmp/kosmtik$ npm install
npm http GET https://registry.npmjs.org/mapnik
npm http 304 https://registry.npmjs.org/mapnik
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> mapnik@3.4.0 install /home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.0/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.0/node-v11-linux-ia32.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.4.0/node-v11-linux-ia32.tar.gz (falling back to source compile with node-gyp) 
make: Entering directory `/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/build'
  ACTION binding_gyp_make_vector_tile_target_generate_protoc_files Release/obj/gen/vector_tile.pb.cc
/bin/sh: 1: protoc: not found
make: *** [Release/obj/gen/vector_tile.pb.cc] Error 127
make: Leaving directory `/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mateusz/Desktop/tmp/kosmtik/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.13.0-55-generic
gyp ERR! command "/usr/bin/nodejs" "/home/mateusz/Desktop/tmp/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik.node" "--module_name=mapnik" "--module_path=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32"
gyp ERR! cwd /home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/mateusz/Desktop/tmp/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik.node --module_name=mapnik --module_path=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:753:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
node-pre-gyp ERR! System Linux 3.13.0-55-generic
node-pre-gyp ERR! command "node" "/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik
node-pre-gyp ERR! node -v v0.10.28
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /home/mateusz/Desktop/tmp/kosmtik/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32/mapnik.node --module_name=mapnik --module_path=/home/mateusz/Desktop/tmp/kosmtik/node_modules/mapnik/lib/binding/node-v11-linux-ia32' (1)
npm ERR! mapnik@3.4.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.4.0 install script.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-55-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/mateusz/Desktop/tmp/kosmtik
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mateusz/Desktop/tmp/kosmtik/npm-debug.log
npm ERR! not ok code 0
```

/home/mateusz/Desktop/tmp/kosmtik/npm-debug.log file is missing.

Or maybe I should report it to maintainers of mapnik package? In that case - is https://github.com/mapnik/mapnik/issues a correct place to report this problem?

**Comment by springmeyer** [comment] 2015-07-07 05:46
https://github.com/mapnik/node-mapnik would be the right place. But I'm the maintainer and noticed this in my github notifications.

The problem is that I provide node-mapnik binaries for 64 bit systems (so install is painless and you don't need an external mapnik). But in your case you appear to be running a 32 bit linux machine. So, the build is falling back to a source compile. And node-mapnik requires libprotobuf and protoc compiler. It is failing because these are not found:

> /bin/sh: 1: protoc: not found

**Comment by matkoniecz** [comment] 2015-07-07 05:58
```
sudo apt-get install libprotobuf-dev protobuf-compiler
```

solved this problem and the next one, but given that https://github.com/mapnik/node-mapnik/issues/473 happened anyway it is not clear whatever installation on 32 bit may work.

In case of success - would be a good idea to add to readme instructions for 32 bit Ubuntu?

**Comment by springmeyer** [comment] 2015-07-07 06:00
I'm curious: why are you using a 32 bit system? I've not built binaries for 32 bit systems because I figure very few people are still using them. Am I wrong?

**Comment by matkoniecz** [comment] 2015-07-07 07:34
I have 32 bit computer. Given that it is recently causing more serious problems I am considering buying a new one.

**Comment by kocio-pl** [comment] 2015-09-23 13:32
I also use 32-bit system just because I just update it everytime there is a new Ubuntu version for a long time, because its easy and it works, and there's no simple way to migrate from 32-bit to 64-bit - in general one have to reinstall the system completely...

**Comment by nebulon42** [comment] 2016-10-14 12:16
Closing since this is a node-mapnik problem.

**Closed by nebulon42** 2016-10-14 12:16 UTC
